services:
  backend:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks: [app]

  web:
    # expose HTTP & HTTPS publicly
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    networks: [app]
    volumes:
      # Keep ACME webroot and cert storage only; Nginx config is baked into the image
      # ACME webroot and cert storage
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
    # run on-demand; no ports

networks:
  app:
    driver: bridge
